apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  ports:
    - port: 8080
  selector:
    app: currencyservice
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: exorath/currencyservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_URI
          value: "<INSERT_URI>"
        - name: DB_NAME
          value: "currencyservice"